Декоративные элементы на внутренней странице
htmlacademy-htmlcss/1973999-sedona-33 pull request #10
Opened 2022-03-20 23:00 UTC by DenisZinev

2022-03-21 18:34 UTC, andreysgra requested changes

2022-03-21 18:34 UTC, andreysgra commented on catalog.html
> +                    </svg>
У домика и ссылок с текстом изменяется непрозрачность, а у стрелки нет.

Но у вас тут ошибка - стрелка это декоративный элемент, разделитель между ссылками. Поэтому неправильно размечать его как ссылку. Нужно добавить как псевдо элемент к `.breadcrumbs-item`.

2022-03-21 18:34 UTC, andreysgra commented on index.html
> +              <a class="navigation-link-text-current" href="index.html">Главная</a>
А класс `navigation-link-text` где? Без него ссылка выглядит вот так:
![image](https://user-images.githubusercontent.com/17790771/159337676-316b809d-a5f7-4ae8-8d80-850ac13b3d22.png)

2022-03-21 18:34 UTC, andreysgra commented on styles/styles.css
> +}
Если элемент позиционируется абсолютно, то он должен быть к чему-то привязан. В данном случае, к ссылке с классом `navigation-link-text-current`. Про [позиционирование](https://up.htmlacademy.ru/htmlcss/33/module/7/item/3).

2022-03-21 18:34 UTC, andreysgra commented on styles/styles.css
> +  height: 120px;
Фиксированная высота подвала. Критерий [TEST-04](https://up.htmlacademy.ru/htmlcss/33/criteries#TEST-04) не пройдёт проверку на переполнение.

2022-03-21 18:34 UTC, andreysgra commented on styles/styles.css
> +}
В коде SVG нужно удалить заливку
![image](https://user-images.githubusercontent.com/17790771/159338728-47d94352-ae63-42f7-be34-49ad6b3f8a18.png)
и закрасить иконку через CSS,

2022-03-21 18:34 UTC, andreysgra commented on styles/styles.css
> +}
Для этого нужно просто разобрать, что вы хотели сделать. Вы изменяете значение свойства `color`. Для чего предназначено это свойство? В ссылке есть текст, цвет которого нужно изменить? В ссылке есть только `img`, цвет которого изменить средствами CSS нельзя. Значит нужен другой подход (вы это уже не однократно делали).

2022-03-21 18:34 UTC, andreysgra commented on styles/styles.css
> +}
Белый то белый, а это что?
![image](https://user-images.githubusercontent.com/17790771/159339557-69726e23-1da0-4438-bbf0-bf1c82dd550c.png)

2022-03-21 18:34 UTC, andreysgra commented on styles/styles.css
> +}
Что не работает?

Нужно добавить паддинги ссылке, тогда тень подвинется на нужное расстояние.

2022-03-21 18:34 UTC, andreysgra commented on styles/styles.css
> +}
А это?
![image](https://user-images.githubusercontent.com/17790771/159339992-d7eb1963-93d8-4326-a93b-536c0e1e49ff.png)

2022-03-21 18:34 UTC, andreysgra commented on styles/styles.css
> +  /* при фокусировке получается большая рамка (?) */
Нужно просто увеличить размеры кнопки. Ну а в целом, есть же свойство `outline` (его кстати браузер используется для собственных стилей `:focus`). Почему вы его не используете? Есть и свойство `outline-offset` для указания расстояния.

2022-03-21 18:34 UTC, andreysgra commented on styles/styles.css
> +  /* не понял, почему данная вкладка в 2 строки (что на нее влияет?) */
Вопроса не понял. Что значит "вкладка в 2 строки"?

2022-03-21 18:34 UTC, andreysgra commented on styles/styles.css
> +  border: 3px solid #E6E6E6;
Ну как так не нашли? Вот же рамка в 2px:
![image](https://user-images.githubusercontent.com/17790771/159340848-23965790-e0bd-4e47-9917-68e12eaf1ee3.png)

2022-03-21 20:39 UTC, DenisZinev commented on styles/styles.css
> +  height: 120px;
Убрал высоту.

2022-03-21 21:01 UTC, DenisZinev commented on styles/styles.css
> +  border: 3px solid #E6E6E6;
У меня в фигме по другому отображается. Бордер так не расписан и позиционирования тоже нет.
Исправил.

2022-03-21 21:10 UTC, DenisZinev commented on styles/styles.css
> +  /* не понял, почему данная вкладка в 2 строки (что на нее влияет?) */
На макете этот раздел (найдено гостиниц - сначала дешевые и переключатели) на одном уровне (в одну линию, т.е. расположены ровно). У меня криво, т.к. под блоком "сначала дешевые" как будто вторая строка, в просмотре кода (при наведении видно).

2022-03-22 17:58 UTC, DenisZinev commented on styles/styles.css
> +}
Спасибо. Понял, добавил.

2022-03-22 18:42 UTC, DenisZinev commented on styles/styles.css
> +  /* при фокусировке получается большая рамка (?) */
Исправил. Нашел размеры рамки фокуса в стайлгайде.

2022-03-22 20:07 UTC, DenisZinev commented on index.html
> +              <a class="navigation-link-text-current" href="index.html">Главная</a>
Вернул обратно.

2022-03-22 20:57 UTC, DenisZinev commented on styles/styles.css
> +}
Добавил подчеркивание.

2022-03-22 21:07 UTC, DenisZinev commented on styles/styles.css
> +}
Добавил прозрачность.

2022-03-22 21:55 UTC, DenisZinev commented on styles/styles.css
> +}
Если пишу над фокусом, значит фокус не работает.
Добавил паддинги.
У дома фокус появился, но не такой как в макете.
У текста - гостиницы фокус не появился.

2022-03-22 22:03 UTC, DenisZinev commented on styles/styles.css
> +}
Исправил. Нашел про это в лайве.

2022-03-22 22:06 UTC, DenisZinev commented on styles/styles.css
> +}
Не понял.
Или перевести в svg и задать как для иконок навигации (подвала)?

2022-03-22 22:16 UTC, DenisZinev commented on catalog.html
> +                    </svg>
Исправил.

2022-03-22 22:30 UTC, DenisZinev commented on catalog.html
> +                    </svg>
Только появилась какая-то фиолетовая черта у правого нижнего угла дома.

2022-03-23 17:14 UTC, merged

2022-03-24 08:04 UTC, andreysgra commented on styles/styles.css
> +}
Конечно, цвет и прочие параметры svg графики можно изменять только тогда, когда код SVG встроен в HTML. Цвет в `img` изменить невозможно, тем более свойством `color`, которое отвечает за цвет шрифта.

2022-03-24 08:09 UTC, andreysgra commented on styles/styles.css
> +  border: 3px solid #E6E6E6;
В фигме не может иначе отображаться. Нужно смотреть во вкладке Inspect (для этого макет должен быть клонирован в вашем аккаунте).
![image](https://user-images.githubusercontent.com/17790771/159870847-5f3dbde0-60ca-468b-abe1-c10424843dbe.png)

2022-03-24 08:13 UTC, andreysgra commented on styles/styles.css
> +  /* не понял, почему данная вкладка в 2 строки (что на нее влияет?) */
Марджины этого параграфа формируют высоту блока `sorting-container`.
![image](https://user-images.githubusercontent.com/17790771/159871366-42447146-841f-4e48-9ab1-ed767afcd4de.png)
Думаю, что они не нужны.

Блок `sorting-container` является флек-контейнером, а за выравнивание флекс-элементов вдоль поперечной оси отвечает свойство `align-items`.

2022-03-24 08:16 UTC, andreysgra commented on catalog.html
> +                    </svg>
Что-то такой черты не наблюдаю.

2022-03-24 08:43 UTC, andreysgra commented on styles/styles.css
> +}
Чтобы состояние фокуса было такое же, как в макете, нужно сформировать у ссылки необходимую геометрию. Сейчас она представляет прямоугольник вот с такими размерами:
![image](https://user-images.githubusercontent.com/17790771/159876908-827f77d0-f6cb-4ec1-83a9-ab985dd08eec.png)