Добавляет catalog.
htmlacademy-htmlcss/1973999-sedona-33 pull request #3
Opened 2022-02-04 19:25 UTC by DenisZinev

2022-02-05 20:38 UTC, andreysgra requested changes

2022-02-05 20:38 UTC, andreysgra commented on catalog.html
> +          <button class="button button-load" type="submit">Загрузить ещё</button>
Дочерними элементами списка могут быть только `<li>`. Кнопку нужно вынести за пределы списка `hotel-list`.

2022-02-05 20:38 UTC, andreysgra commented on catalog.html
> +          </select>
Также, как и в случае со списком гостиниц - `<span>` и `<select>` нужно вынести за пределы списка.

2022-02-05 20:38 UTC, andreysgra commented on catalog.html
> +            <a class="hotel-card-price">Гостиница от 4000 ₽</a>
Для этого текста ссылка не нужна, а вот тип жилья и его стоимость следует разнести по разным тегам.

2022-02-05 20:38 UTC, andreysgra commented on catalog.html
> +            <!-- Рейтинг(?) -->
Это звёздность гостиницы
![image](https://user-images.githubusercontent.com/17790771/152658079-b33cfd93-24ed-4823-ab0c-11eeb33f6ea7.png)
Можно сделать под неё заготовку в виде `div` (в дальнейшем звёзды добавим фоновым рисунком).

А вот рейтинг
![image](https://user-images.githubusercontent.com/17790771/152658122-e983de06-5b23-4aa5-a813-cf11fb1a0bbd.png)
нужно добавить в разметку.

2022-02-06 12:02 UTC, DenisZinev commented on catalog.html
> +          <button class="button button-load" type="submit">Загрузить ещё</button>
Спасибо. Исправил. Нужно было проверить весь код в валидаторе.

2022-02-06 12:27 UTC, DenisZinev commented on catalog.html
> +          </select>
Спасибо. Исправил.

2022-02-06 14:27 UTC, DenisZinev commented on catalog.html
> +            <!-- Рейтинг(?) -->
Спасибо. Исправил.

2022-02-06 15:26 UTC, DenisZinev commented on catalog.html
> +            <a class="hotel-card-price">Гостиница от 4000 ₽</a>
Да не нужна (copy paste). Спасибо, исправил.

2022-02-06 15:28 UTC, DenisZinev commented
Все исправил.

2022-02-06 19:16 UTC, merged