Базовая стилизация всех страниц.
htmlacademy-htmlcss/1973999-sedona-33 pull request #5
Opened 2022-02-13 19:56 UTC by DenisZinev

2022-02-14 10:23 UTC, andreysgra requested changes

2022-02-14 10:23 UTC, andreysgra commented on styles/styles.css
> +  background-position: top;
На `.main-index` не нужно навешивать фоновое изображение. Логотип "welcome" оберните в `div` и задайте этому блоку фоновое изображение гор.

2022-02-14 10:23 UTC, andreysgra commented on styles/styles.css
> +}
Более правильным решением будет изменение названия класса у последних трёх элементов списка `advantages-list`. Как мы видим, их стилизация кардинально отличается от первых двух элементов, поэтому и нет необходимости им иметь одинаковые классы.

`:nth-child` структурный псевдо класс и стилизация по нему жёстко привязана к порядку HTML элементов. Стоит порядок изменить и нарушится стилизация. Поэтому использованием `:nth-child` лучше не злоупотреблять. Однако из `:nth-child` можно извлечь и определённую пользу, если использовать его с умом: в последних трёх элементах списка `advantages-list` меняется цвет заливки и в ней есть закономерность: у нечётных блоков один цвет, у чётных другой. Мы можем использовать для `:nth-child` ключевые слова `odd` и `even`, например `:nth-child(odd)`.

2022-02-14 10:23 UTC, andreysgra commented on styles/styles.css
> +
Смешанный цвет вы не можете задать, да и такого в макете нет. Нужно просто пересмотреть подход к разметке и свойствам CSS. Заливку вы применяете к родительскому `advantages-item`, соответственно она передаётся и потомкам (точнее не передаётся, а просвечивает сквозь них, так как по умолчанию цвет заливки прозрачный). Нужно поступить так: контент первой причины (за исключением вложенного списка `service-list`) обернуть в `div` и заливку цветом перенести в него. В блоке второй причины нет вложенного списка, но такую же обёртку нужно сделать и в нём для единообразия.

2022-02-14 10:23 UTC, andreysgra commented on styles/styles.css
> +  background-repeat: no-repeat;
Также, как и на главной странице, не нужно фон навешивать на `main`. Если бы фон растягивался в макете на всю страницу, это было бы оправдано, но мы видим, что фон присутствует только в блоке с формой, соответственно его и нужно применить к этому блоку, но для этого нужно кое-что изменить в разметке: создать новый блок, сразу же после открывающего тега `main` и перенести в него `inner-header` и `hotels-filter`.

```
<main>
  <div>
    <header class="inner-header">
    </header>

    <form class="hotels-filter">
    </form>
  </div>
</main>
```

2022-02-14 10:23 UTC, andreysgra commented on styles/styles.css
> +  font-family: "PT Sans", sans-serif;
Можно сделать проще: `font-family: inherit` для наследования значения свойства. (Так же и остальным кнопкам).

2022-02-15 18:15 UTC, DenisZinev commented on styles/styles.css
> +  font-family: "PT Sans", sans-serif;
Исправил.

2022-02-15 19:44 UTC, DenisZinev commented on styles/styles.css
> +  background-repeat: no-repeat;
Исправил.

2022-02-15 21:38 UTC, DenisZinev commented on styles/styles.css
> +}
Изменил. Разметка до этого была принята (соответственно написал псевдо классы именно под то, что было согласовано).

2022-02-16 08:26 UTC, andreysgra commented on styles/styles.css
> +}
На этапе выполнения задания по разметке мы делаем разные допущения и упрощения. С точки зрения структуры документа там всё правильно, но когда начинается стилизация,  то порой приходится что добавлять и изменять.

2022-02-16 19:20 UTC, DenisZinev commented on styles/styles.css
> +  background-position: top;
Исправил.

2022-02-16 19:20 UTC, DenisZinev commented on styles/styles.css
> +}
Ок. Понятно.

2022-02-16 19:21 UTC, DenisZinev commented on styles/styles.css
> +
Понял. Разобрался. Исправил.

2022-02-16 19:22 UTC, DenisZinev commented
Все замечания учтены.

2022-02-16 20:40 UTC, merged