Микросетки на флексах для всех страниц
htmlacademy-htmlcss/1973999-sedona-33 pull request #7
Opened 2022-02-27 16:10 UTC by DenisZinev

2022-02-28 20:12 UTC, andreysgra requested changes

2022-02-28 20:12 UTC, andreysgra commented on styles/styles.css
> +  padding: 20px 17px;
А вот превращение ссылок из навигации в блочный элемент выглядит очень странно. Вы этими свойствами сформировали геометрию ссылок, которой не должно быть. И вот эта вся область вокруг ссылки стала кликабельной, что вводит пользователя в заблуждение
![image](https://user-images.githubusercontent.com/17790771/154117295-efac42f0-6b50-4165-a368-add241b70064.png)
Если бы ссылка выглядела как кнопка (например `.navigation-button`), то данные свойства были бы нужны.

То, что показано в демо, применительно к проекту барбершоп, но проекты отличаются друг от друга. В барбершопе сделано так, потому что ссылки в меню выглядят как кнопки (можно понять по стайлгайду), но в седоне они выглядят как обычный текст, следовательно к ним не нужно применять блочную модель и паддинги. Нужно убрать у ссылок меню (именно у них) display: block и паддинги.

P.S. Типичная ошибка всех студентов, кто выбрал седону.

2022-02-28 20:12 UTC, andreysgra commented on styles/styles.css
> +  display: flex;
Почему не `display: block`? Что вам нужно от ссылки-кнопки: всего лишь, чтобы учитывались вертикальные марджины. Для этого достаточно блочной модели.

2022-02-28 20:12 UTC, andreysgra commented on styles/styles.css
> +  flex-wrap: wrap;
Есть ощущение, что `div` с классом `page-footer-container` является лишней обёрткой (а у нас есть базовый критерий про лишние HTML элементы). Ведь флекс-контейнером вполне может быть `page-footer` и `page-footer-container` совершенно ни к чему.

2022-02-28 20:12 UTC, andreysgra commented on styles/styles.css
> +  padding-top: 42px;
А почему `padding-top`, а не `margin-top`? Чтобы оттолкнуть блок от соседнего используют внешние отступы, а для создания "воздуха" внутри блока используют внутренние отступы.

2022-02-28 20:12 UTC, andreysgra commented on styles/styles.css
> +  padding-bottom: 5px;
В заголовке, логичнее было бы не обнулять марджины и заменять их на паддинги, а изменить стандартные значения марджинов `h1` на нужную величину.

Есть момент - "выпадение" вертикальных марджинов дочернего элемента из родительского, если у того нет вертикальных паддингов или рамок, поэтому вы и решили проблему так. Но стоит добавить для `inner-header` вертикальные паддинги, а у `inner-header` подкорректировать значение марджинов.

2022-02-28 20:12 UTC, andreysgra commented on styles/styles.css
> +  text-align: center;
Лучше `min-height` вместо `height`.

В барбершопе всё сделано правильно - центрирование текста за счёт вертикальных паддингов и вам нужно сделать также. Приблизительно можно рассчитать так: (высота ссылки - высота линии текста) / 2. Но всё равно в дальнейшем, в процессе работы над PP нужно будет делать подгонку вручную.

2022-02-28 20:12 UTC, andreysgra commented on styles/styles.css
> +}
`margin-left: auto` для `hotel-page` (блока-родителя). Ну и также желательно `hotel-page` задать значение `width` явно, так как без этого ширина флекс-контейнера равна ширине его элементов.

2022-03-01 19:53 UTC, DenisZinev commented on styles/styles.css
> +  padding: 20px 17px;
Исправил. Я знаю, что это не кнопки и сделал так исходя из того, что у пользователя появляется возможность кликнуть не только на саму ссылку, но и рядом.

2022-03-01 20:11 UTC, DenisZinev commented on styles/styles.css
> +  display: flex;
Исправил.

2022-03-01 20:59 UTC, DenisZinev commented on styles/styles.css
> +  flex-wrap: wrap;
Исправил. Согласен, лишнее.

2022-03-01 21:02 UTC, DenisZinev commented on styles/styles.css
> +  padding-top: 42px;
Исправил.

2022-03-01 21:14 UTC, DenisZinev commented on styles/styles.css
> +  text-align: center;
Исправил.

2022-03-01 21:37 UTC, DenisZinev commented on styles/styles.css
> +}
Добавил margin-left: auto, помогло. Ширина сортировки задана по макету 160рх, чтобы отодвинуть текст "гостиниц на странице", задал для .select-number-page margin-left: 51px (согласно макета).

2022-03-01 22:02 UTC, DenisZinev commented on styles/styles.css
> +  padding-bottom: 5px;
Исправил, насколько понял.

2022-03-02 19:06 UTC, andreysgra commented on styles/styles.css
> +  padding: 20px 17px;
Дело в том, что эта вёрстка не адаптивная, то есть не предназначена и не очень удобна для просмотра на мобильных устройствах. Да, на мобильном устройстве так было бы пользователю удобнее.

2022-03-02 19:09 UTC, andreysgra commented on styles/styles.css
> +  padding-bottom: 5px;
Да, правильно.

2022-03-02 19:10 UTC, merged