Декоративные элементы на главной странице
htmlacademy-htmlcss/1973999-sedona-33 pull request #9
Opened 2022-03-13 19:52 UTC by DenisZinev

2022-03-14 16:03 UTC, andreysgra requested changes

2022-03-14 16:03 UTC, andreysgra commented on index.html
> +                    <clipPath id="a">
Похоже, что `id` нужно убрать, так как возникает ошибка валидации HTML:
![image](https://user-images.githubusercontent.com/17790771/158208081-44d09a82-1972-4d1c-a563-9bbcef094291.png)

2022-03-14 16:03 UTC, andreysgra commented on styles/styles.css
> +/* Не понимаю, как выровнять текст в навигации */
1. Нужно обнулить дефолтные стили списков:
![image](https://user-images.githubusercontent.com/17790771/158208780-79e22558-34fc-4735-bd05-035824efaf63.png)
(оранжевым цветов в Dev tools браузера отображаются `margin`, а зелёным `padding`.
2. Навигации `.navigation` задать выравнивание флекс элементов по центру (свойство `align-items`).

2022-03-14 16:03 UTC, andreysgra commented on styles/styles.css
> +  display: block;
Необходимости превращать ссылки в блочные элементы, задавать им `position: relative` и `margin-top`, `margin-right` нет необходимости. Всё, что нужно сделать, написал выше.

2022-03-14 16:03 UTC, andreysgra commented on styles/styles.css
> +}
Все эти свойства и абсолютное позиционирование иконкам в этих ссылках не нужны.
1. Этим ссылкам нужно применить другие классы. Класс `navigation-link` вы используете для текстовых ссылок в меню, а эти ссылки ни визуально, ни логически не имеют ничего общего со ссылками меню.
![image](https://user-images.githubusercontent.com/17790771/158209761-11b58a2f-17a2-4a0b-896d-4defb3deb282.png)
2. Эти ссылки нужно сделать флекс-контейнером, задать им `width` и `height` и свойства `justify-content`, `align-items` чтобы расположить иконки по центру ссылки.

2022-03-14 16:03 UTC, andreysgra commented on styles/styles.css
> +  margin: 0 auto;
Какая здесь ошибка: выше вы задаёте значения для свойств `margin-top`, `margin-bottom`, `margin-right`, а потом всё это обнуляете с помощью `margin: 0 auto`. В целом здесь свойство `margin` скорее всего не понадобится, если сделаете так, как я написал в первом комментарии.

2022-03-14 16:03 UTC, andreysgra commented on styles/styles.css
> +  background-position: 50% 30%;
Второй параметр не задавать в процентах, а задать в пикселах. Можно задать пока приблизительно, а при наложении PP уже подобрать значение изменяя параметр свойства в Dev tools.

2022-03-14 16:03 UTC, andreysgra commented on styles/styles.css
> +  /* паддинги слева и справа по макету не измерить, поэтому указал примерно */
На данном этапе такое решение нормально и при подгонке по PP параметры подбираются в Dev tools браузера.

2022-03-14 16:03 UTC, andreysgra commented on styles/styles.css
> +  margin: 0;
`.field` это поле формы `input` и по умолчанию у `input` нет `margin`, так что обнулять это свойство нет необходимости.

2022-03-14 16:03 UTC, andreysgra commented on styles/styles.css
> +}
Точно так же, как и ссылками в навигации: абсолютное позиционирование для иконки не нужно. Логичнее сделать ссылку флекс контейнером и выровнять иконку по центру относительно осей.

2022-03-14 20:54 UTC, DenisZinev commented on index.html
> +                    <clipPath id="a">
Скопировал объект svg по-другому из фигмы (получилось без id).

2022-03-14 21:13 UTC, DenisZinev commented on styles/styles.css
> +/* Не понимаю, как выровнять текст в навигации */
Спасибо. Исправил. Про цвета отступов в курсе.

2022-03-14 21:15 UTC, DenisZinev commented on styles/styles.css
> +  display: block;
Исправил.
margin-right оставил, без него нет отступов между словами.

2022-03-14 21:59 UTC, DenisZinev commented on styles/styles.css
> +  margin: 0 auto;
Убрал все margin.

2022-03-14 22:00 UTC, DenisZinev commented on styles/styles.css
> +}
Исправил, но визуально видно, что иконки расположены не по центру.

2022-03-14 22:00 UTC, DenisZinev commented on styles/styles.css
> +  /* паддинги слева и справа по макету не измерить, поэтому указал примерно */
Ок.

2022-03-14 22:06 UTC, DenisZinev commented on styles/styles.css
> +  background-position: 50% 30%;
Исправил.

2022-03-14 22:09 UTC, DenisZinev commented on styles/styles.css
> +  margin: 0;
Исправил.

2022-03-14 22:31 UTC, DenisZinev commented on styles/styles.css
> +}
Исправил. В демо сделаны все иконки через позиционирование и в навигации тоже.

2022-03-14 22:32 UTC, DenisZinev commented
Откорректировал.

2022-03-15 08:51 UTC, andreysgra commented on styles/styles.css
> +}
Нужно сами ссылки превратить во флекс контейнер.
Для `navigation-link` задать `display: flex`, `justify-content: center`, `align-items: center`, а также сформировать геометрию ссылки - задать ей значения `width` и `height`. `width` и `height` по макету вычислить не получится, а значит его нужно подобрать самостоятельно: у вас есть две ссылки `navigation-link` с иконками и можно визуально представить, что ссылка представляет собой квадрат, а значит `width` = `height` . Размеры этих свойств задать исходя из общих размеров всех элементов находящихся в навигации `navigation`: высота не должна превышать высоту `navigation`, но и не быть меньше, чем высота самой большой иконки.

2022-03-15 08:52 UTC, andreysgra commented on styles/styles.css
> +}
А вот эта обёртка лишняя
![image](https://user-images.githubusercontent.com/17790771/158340909-914cf573-7da9-402d-8d75-d120f6f37103.png)
и кроме того валидация HTML не проходит
![image](https://user-images.githubusercontent.com/17790771/158341029-ef08f79f-7722-4e02-8421-f56ad17adf5a.png)

2022-03-15 08:54 UTC, andreysgra commented on styles/styles.css
> +}
Можно и так, через позиционирование, но с флексами выглядит удачнее.

2022-03-15 08:57 UTC, andreysgra commented on styles/styles.css
> +}
Здесь также, как и с `navigation-link` - флекс нужно применить не к `footer-social-list` (это ничего не даёт), а к ссылке в которой лежит иконка
![image](https://user-images.githubusercontent.com/17790771/158341769-3b7ecfdc-897e-4986-a075-90593e7e18cb.png)
Ссылке необходимо задать `width` и `height`.

2022-03-15 08:57 UTC, merged